apiVersion: v1
kind: Namespace
metadata:
  name: develop
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy-develop
  namespace: develop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-develop
  template:
    metadata:
      labels:
        app: backend-develop
    spec:
      containers:
      - name: backend
        image: lucaslpdacosta/backend-develop
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service-develop
  namespace: develop
spec:
  selector:
    app: backend-develop
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-develop-backend
  namespace: develop
spec:
  ingressClassName: nginx
  rules:
  - host: backdevelop.10.48.8.15.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-service-develop
            port:
              number: 3000
---
apiVersion: v1
kind: Namespace
metadata:
  name: develop
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy-develop
  namespace: develop
  labels:
    app: develop
spec:
  selector:
    matchLabels:
      app: frontend-develop
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-develop
    spec:
      containers:
      - name: frontend
        image: lucaslpdacosta/frontend-develop
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service-develop
  namespace: develop
spec:
  type: ClusterIP
  selector:
    app: frontend-develop
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-develop-frontend
  namespace: develop
spec:
  ingressClassName: nginx
  rules:
  - host: frontdevelop.10.48.9.22.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service-develop
            port:
              number: 80